apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: docker-engear-fe-c
          image: sergy98/docker-engear-fe-i:0.2
          resources:
            limits:
              memory: "384Mi"
              cpu: "500m"
          ports:
            - containerPort: 5173
